name: flutter_blue_plus_example
description: Demonstrates how to use the flutter_blue_plus plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter

  flutter_blue_plus: ^1.34.4
  flutter_svg: ^2.0.14
  dio: ^5.7.0


flutter:
  uses-material-design: true
  assets:
    - lib/assets/icon/spo2.svg
    - lib/assets/images/anh.png

